name: Update packages

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Pipenv lock
        id: pipenv_lock
        uses: Breakthrough-Energy/actions/update-packages@main

      - name: Parse JSON
        id: parse_json
        run: |
             additions=$(echo $json_summary | jq '.Additions')
             additions="${additions//$'\n'/'%0A'}"
             echo "::set-output name=additions::$additions"
             deletions=$(echo $json_summary | jq '.Deletions')
             deletions="${deletions//$'\n'/'%0A'}"
             echo "::set-output name=deletions::$deletions"
             updates=$(echo $json_summary | jq '.Updates')
             updates="${updates//$'\n'/'%0A'}"
             echo "::set-output name=updates::$updates"
        env:
          json_summary: ${{ steps.pipenv_lock.outputs.summary }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CI_TOKEN_CLONE_REPO }}
          commit-message: Update dependencies
          title: Update dependencies
          labels: dependencies
          delete-branch: true
          body: |
            ### Summary of changes

            - Additions
            ```
              ${{ steps.parse_json.outputs.additions }}
            ```
            - Deletions
            ```
              ${{ steps.parse_json.outputs.deletions }}
            ```
            - Updates
            ```
              ${{ steps.parse_json.outputs.updates }}
            ```

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
